[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[tracing_server]
enabled = false
port = 5555

[[chains]]
id = "uni-6"
memo_prefix = "Relayed by Alex Cryp"

rpc_addr = 'https://juno-testnet-rpc.polkachu.com/'
grpc_addr = 'http://juno-testnet-grpc.polkachu.com:12690/'
# websocket_addr = "wss://juno-testnet-rpc.polkachu.com/websocket"

event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '20s'
account_prefix = 'juno'
key_name = 'juno'
store_prefix = 'ibc'
max_tx_size = 180000
max_msg_num=15
max_gas= 2000000
gas_price = { price = 0.025, denom = 'ujunox' }
gas_multiplier = 1.2
max_block_time = '10s'
clock_drift = '5s'
trusting_period = '3days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = "allow"
list = [["wasm.juno1wjjx974u9j80wazvxsx3ukr85jmazk7szk37qn0kmelu98gl620qwxqxz0", "channel-839"], ["wasm.osmo1xz00vhlm7e3ysj9f2v3jtcjpqvectwgdkkxuau8rw290ys087s6qtk24hy", "channel-4347"]]

[[chains]]
id = "osmo-test-5"
memo_prefix = "Relayed by Alex Cryp"

rpc_addr = "https://rpc.osmotest5.osmosis.zone/"
grpc_addr = "https://grpc.osmotest5.osmosis.zone/"
# websocket_addr = "wss://rpc.osmotest5.osmosis.zone:433/websocket"

event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '20s'
account_prefix = 'osmo'
key_name = 'osmo'
store_prefix = 'ibc'
max_tx_size = 180000
max_msg_num=15
max_gas= 2000000
gas_price = { price = 0.025, denom = 'uosmo' }
gas_multiplier = 1.2
max_block_time = '10s'
clock_drift = '5s'
trusting_period = '3days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = "allow"
list = [["wasm.juno1wjjx974u9j80wazvxsx3ukr85jmazk7szk37qn0kmelu98gl620qwxqxz0", "channel-839"], ["wasm.osmo1xz00vhlm7e3ysj9f2v3jtcjpqvectwgdkkxuau8rw290ys087s6qtk24hy", "channel-4347"]]
